//
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#include <string>

#include "google/spanner/admin/database/v1/common.pb.h"
#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "googlesql/base/testing/status_matchers.h"
#include "tests/common/proto_matchers.h"
#include "absl/status/status.h"
#include "tests/conformance/common/database_test_base.h"

namespace google {
namespace spanner {
namespace emulator {
namespace test {

namespace {

using googlesql_base::testing::StatusIs;

class QueryHintsTest
    : public DatabaseTest,
      public testing::WithParamInterface<database_api::DatabaseDialect> {
 public:
  void SetUp() override {
    dialect_ = GetParam();
    DatabaseTest::SetUp();
  }

  absl::Status SetUpDatabase() override {
    return SetSchemaFromFile("query_hints.test");
  }
};

INSTANTIATE_TEST_SUITE_P(
    PerDialectQueryHintsTest, QueryHintsTest,
    testing::Values(database_api::DatabaseDialect::GOOGLE_STANDARD_SQL,
                    database_api::DatabaseDialect::POSTGRESQL),
    [](const testing::TestParamInfo<QueryHintsTest::ParamType>& info) {
      return database_api::DatabaseDialect_Name(info.param);
    });

TEST_P(QueryHintsTest, QueryWithHintsForceIndex) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GOOGLESQL_EXPECT_OK(Query(
        "SELECT ID, Name, Age FROM Users /* @force_index=UsersByName */"));

    // PostgreSQL ignores the index hint instead of failing.

    GOOGLESQL_EXPECT_OK(Query(
        "/* @force_index=$base_table */ SELECT ID, Name, Age FROM Users"));
  } else {
    GOOGLESQL_EXPECT_OK(
        Query("SELECT ID, Name, Age FROM Users@{force_index=UsersByName}"));
    EXPECT_THAT(
        Query("@{force_index=UsersByName} SELECT ID, Name, Age FROM Users"),
        StatusIs(absl::StatusCode::kInvalidArgument));
    GOOGLESQL_EXPECT_OK(
        Query("@{force_index=_BASE_TABLE} SELECT ID, Name, Age FROM Users"));
  }
}

TEST_P(QueryHintsTest, QueryWithHintsForceIndexManagedIndex) {
  // Managed indexes should work for force_index query hint.
  // The last part of the index name is not used for matching the index in the
  // emulator, but this test uses the production generated fingerprint to pass
  // internal conformance tests.
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GOOGLESQL_EXPECT_OK(Query(
        "SELECT X FROM "
        "Referencing /* @force_index=IDX_Referencing_X_Y_107FF16042DE7637 */"));
    // PostgreSQL ignores the index hint instead of failing.
  } else {
    GOOGLESQL_EXPECT_OK(Query(
        "SELECT X FROM "
        "Referencing@{force_index=IDX_Referencing_X_Y_107FF16042DE7637}"));
    // Cannot use managed indexes generated by the emulator for force_index.
    EXPECT_THAT(
        Query("SELECT X FROM "
              "Referencing@{force_index=IDX_Referencing_X_Y_108BAA6EDCE3C50C}"),
        StatusIs(absl::StatusCode::kInvalidArgument));
  }
}

TEST_P(QueryHintsTest, QueryWithHintsIndexStrategy) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GOOGLESQL_EXPECT_OK(
        Query("SELECT ID, Name, Age FROM Users /* @"
              "index_strategy=force_index_union */"));
    GOOGLESQL_EXPECT_OK(
        Query("/* @INDEX_STRATEGY=FORCE_INDEX_UNION */ SELECT ID, Name, Age "
              "FROM Users"));
    // PostgreSQL ignores index strategy hint instead of failing.
  } else {
    GOOGLESQL_EXPECT_OK(Query(
        "SELECT ID, Name, Age FROM Users@{index_strategy=force_index_union}"));
    GOOGLESQL_EXPECT_OK(Query(
        "@{INDEX_STRATEGY=FORCE_INDEX_UNION} SELECT ID, Name, Age FROM Users"));
    EXPECT_THAT(Query("@{index_strategy=invalid_value} SELECT ID, Name, Age "
                      "FROM Users"),
                StatusIs(absl::StatusCode::kInvalidArgument));
  }
}

TEST_P(QueryHintsTest, QueryWithHintsJoinMethod) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GOOGLESQL_EXPECT_OK(
        Query("/* @join_method=merge_join */ SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("/* @join_method=hash_join */ SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("/* @join_method=apply_join */ SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("/* @join_method=loop_join */ SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(Query(
        "/* @join_method=push_broadcast_hash_join */ SELECT ID, Name, Age FROM "
        "Users"));
  } else {
    GOOGLESQL_EXPECT_OK(
        Query("@{join_method=merge_join} SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("@{join_method=hash_join} SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("@{join_method=apply_join} SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("@{join_method=loop_join} SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(Query(
        "@{join_method=push_broadcast_hash_join} SELECT ID, Name, Age FROM "
        "Users"));
  }
}

TEST_P(QueryHintsTest, QueryHintsWithScanMethod) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GOOGLESQL_EXPECT_OK(
        Query("/* @scan_method=batch */ SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(Query("/* @scan_method=row */ SELECT ID, Name, Age FROM Users"));
    // PostgreSQL ignores the scan method hint instead of failing.
  } else {
    GOOGLESQL_EXPECT_OK(Query("@{scan_method=batch} SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(Query("@{scan_method=row} SELECT ID, Name, Age FROM Users"));
    EXPECT_THAT(Query("@{scan_method=invalid} SELECT ID, Name, Age FROM Users"),
                StatusIs(absl::StatusCode::kInvalidArgument));
  }
}

TEST_P(QueryHintsTest, QueryWithHintsJoinType) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GOOGLESQL_EXPECT_OK(
        Query("/* @join_type=hash_join */ SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("/* @join_type=apply_join */ SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("/* @join_type=loop_join */ SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("/* @join_type=push_broadcast_hash_join */ SELECT ID, Name, Age "
              "FROM Users"));
  } else {
    GOOGLESQL_EXPECT_OK(Query("@{join_type=hash_join} SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(Query("@{join_type=apply_join} SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(Query("@{join_type=loop_join} SELECT ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("@{join_type=push_broadcast_hash_join} SELECT ID, Name, Age FROM "
              "Users"));
  }
}

TEST_P(QueryHintsTest, QueryWithHintsHashJoinBuildSide) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    // PostgreSQL ignores the join hint instead of failing.

    GOOGLESQL_EXPECT_OK(Query(
        "/* @join_type=hash_join,hash_join_build_side=build_right */ SELECT "
        "ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(Query(
        "SELECT a.ID, b.Name FROM Users a JOIN /* @"
        "join_method=hash_join,hash_join_build_side=build_right */ Users b "
        "ON false"));
  } else {
    EXPECT_THAT(Query("@{hash_join_build_side=build_left} SELECT ID, Name, Age "
                      "FROM Users"),
                StatusIs(absl::StatusCode::kInvalidArgument));
    GOOGLESQL_EXPECT_OK(
        Query("@{join_type=hash_join,hash_join_build_side=build_right} SELECT "
              "ID, Name, Age FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("SELECT a.ID, b.Name FROM Users a HASH JOIN "
              "@{hash_join_build_side=build_right} Users b "
              "ON false"));
  }
}

TEST_P(QueryHintsTest, QueryWithGroupHints) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GOOGLESQL_EXPECT_OK(Query(
        "SELECT 1 FROM Users GROUP BY /* @group_method=hash_group */ Name"));
    GOOGLESQL_EXPECT_OK(Query(
        "SELECT 1 FROM Users GROUP BY /* @group_method=stream_group */ Name"));
    GOOGLESQL_EXPECT_OK(Query(
        "SELECT 1 FROM Users GROUP BY /* @group_type=hash_group */ Name"));
    GOOGLESQL_EXPECT_OK(Query(
        "SELECT 1 FROM Users GROUP BY /* @group_type=stream_group */ Name"));
  } else {
    GOOGLESQL_EXPECT_OK(
        Query("SELECT 1 FROM Users GROUP @{group_method=hash_group} BY Name"));
    GOOGLESQL_EXPECT_OK(Query(
        "SELECT 1 FROM Users GROUP @{group_method=stream_group} BY Name"));
    GOOGLESQL_EXPECT_OK(
        Query("SELECT 1 FROM Users GROUP @{group_type=hash_group} BY Name"));
    GOOGLESQL_EXPECT_OK(
        Query("SELECT 1 FROM Users GROUP @{group_type=stream_group} BY Name"));
  }
}

// Hints for engines other than spanner are ignored.
TEST_P(QueryHintsTest, QueryWithOtherEngineHints) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GOOGLESQL_EXPECT_OK(Query(
        "SELECT 1 FROM Users GROUP BY /* @otherengine.something=1 */ Name"));
  } else {
    GOOGLESQL_EXPECT_OK(
        Query("SELECT 1 FROM Users GROUP @{otherengine.something=1} BY Name"));
  }
}

TEST_P(QueryHintsTest, InvalidIndexHintInQueryReturnsError) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GTEST_SKIP() << "PostgreSQL ignores the index hint instead of failing";
  }

  EXPECT_THAT(Query("SELECT Name FROM Users"
                    "@{force_index=MessagesBySubject}"),
              StatusIs(absl::StatusCode::kInvalidArgument));
}

TEST_P(QueryHintsTest, InvalidIndexHintInDMLReturnsError) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GTEST_SKIP() << "PostgreSQL ignores the index hint instead of failing";
  } else {
    EXPECT_THAT(
        Query("INSERT INTO Users(ID, Name) SELECT "
              "UserId,Subject FROM Messages@{force_index=UsersByName} "),
        StatusIs(absl::StatusCode::kInvalidArgument));

    EXPECT_THAT(
        CommitDml({SqlStatement(
            "UPDATE Users SET Name = 'Peter' "
            "WHERE ID IN "
            "(SELECT MessageId FROM Messages@{force_index=UsersByName})")}),
        StatusIs(absl::StatusCode::kInvalidArgument));
  }
}

TEST_P(QueryHintsTest, InvalidNullFilteredIndexHint) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GTEST_SKIP() << "PostgreSQL ignores the index hint instead of failing";
  }

  EXPECT_THAT(Query("SELECT ID FROM Users@{force_index=UsersByAge}"),
              StatusIs(absl::StatusCode::kInvalidArgument));

  // Null filtered index on (nullable, non-nullable) column.
  EXPECT_THAT(Query("SELECT MessageId FROM Messages"
                    "@{force_index=MessagesByIdAndSubject}"),
              StatusIs(absl::StatusCode::kInvalidArgument));
}

TEST_P(QueryHintsTest, ValidNullFilteredIndexHint) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GOOGLESQL_EXPECT_OK(
        Query("SELECT ThreadId FROM "
              "Messages /* @force_index=MessagesByIdAndThread */"));
  } else {
    GOOGLESQL_EXPECT_OK(
        Query("SELECT ThreadId FROM "
              "Messages@{force_index=MessagesByIdAndThread}"));
  }
}

TEST_P(QueryHintsTest, DisableNullFilteredIndexCheckForValidQuery) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GTEST_SKIP() << "PostgreSQL ignores the index hint instead of failing";
  }

  std::string valid_query =
      "SELECT ID FROM Users@{force_index=UsersByAge} "
      "WHERE Age IS NOT NULL";
  std::string modified_valid_query =
      "SELECT ID FROM Users@{force_index=UsersByAge, "
      "spanner_emulator.disable_query_null_filtered_index_check=true} "
      "WHERE Age IS NOT NULL";

  // The query is accepted in prod but rejected by the Emulator as it currently
  // cannot determine nullability from the predicate."
  if (in_prod_env()) {
    GOOGLESQL_EXPECT_OK(Query(valid_query));
  } else {
    EXPECT_THAT(Query(valid_query),
                StatusIs(absl::StatusCode::kInvalidArgument));
  }

  // With the hint to disable null-filtered checks, the emulator is pacified.
  GOOGLESQL_EXPECT_OK(Query(modified_valid_query));
}

TEST_P(QueryHintsTest, DisableNullFilteredIndexAtStatementLevel) {
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    GOOGLESQL_EXPECT_OK(Query(
        "/* @spanner_emulator.disable_query_null_filtered_index_check=true */ "
        "SELECT ID FROM Users /* @force_index=UsersByAge */ "
        "WHERE Age IS NOT NULL"));
  } else {
    GOOGLESQL_EXPECT_OK(Query(
        "@{spanner_emulator.disable_query_null_filtered_index_check=true} "
        "SELECT ID FROM Users@{force_index=UsersByAge} "
        "WHERE Age IS NOT NULL"));
  }
}

TEST_P(QueryHintsTest, IgnoreUnknownHintsFailsOnUnknownHintByDefault) {
  if (in_prod_env()) {
    GTEST_SKIP() << "ignore_unknown_hints is a spanner_emulator only hint";
  }
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    // In PG, Spanner-specific hints must use the '/*@ ... */' syntax (no space
    // after '/*'). If there is a space (like '/* @'), it is treated as a
    // regular comment and ignored.

    // Unknown hint alone should fail.
    EXPECT_THAT(Query("/*@ unknown_hint=true */ SELECT ID FROM Users"),
                StatusIs(absl::StatusCode::kInvalidArgument));
  } else {
    // Google Standard SQL
    EXPECT_THAT(Query("@{unknown_hint=true} SELECT ID FROM Users"),
                StatusIs(absl::StatusCode::kInvalidArgument));
  }
}

TEST_P(QueryHintsTest, IgnoreUnknownHintsInvalidQualifierFails) {
  if (in_prod_env()) {
    GTEST_SKIP() << "ignore_unknown_hints is a spanner_emulator only hint";
  }
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    // Using spanner qualifier (or empty) for ignore_unknown_hints should fail
    // (since it's an emulator-only hint).
    EXPECT_THAT(
        Query("/*@ ignore_unknown_hints=true, unknown_hint=true */ SELECT ID "
              "FROM Users"),
        StatusIs(absl::StatusCode::kInvalidArgument));
    EXPECT_THAT(
        Query("/*@ spanner.ignore_unknown_hints=true, unknown_hint=true */ "
              "SELECT ID FROM Users"),
        StatusIs(absl::StatusCode::kInvalidArgument));
  } else {
    // Using spanner qualifier (or empty) for ignore_unknown_hints should fail.
    EXPECT_THAT(
        Query("@{ignore_unknown_hints=true, unknown_hint=true} SELECT ID FROM "
              "Users"),
        StatusIs(absl::StatusCode::kInvalidArgument));
    EXPECT_THAT(
        Query("@{spanner.ignore_unknown_hints=true, unknown_hint=true} SELECT "
              "ID FROM Users"),
        StatusIs(absl::StatusCode::kInvalidArgument));
  }
}

TEST_P(QueryHintsTest, IgnoreUnknownHintsValidHintIgnoresUnknowns) {
  if (in_prod_env()) {
    GTEST_SKIP() << "ignore_unknown_hints is a spanner_emulator only hint";
  }
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    // Unknown hint with spanner_emulator.ignore_unknown_hints=true should
    // succeed.
    GOOGLESQL_EXPECT_OK(Query(
        "/*@ spanner_emulator.ignore_unknown_hints=true, unknown_hint=true */ "
        "SELECT ID FROM Users"));

    // Unknown hint with spanner_emulator.ignore_unknown_hints=true should
    // succeed.
    GOOGLESQL_EXPECT_OK(
        Query("/*@ spanner_emulator.ignore_unknown_hints=true, "
              "spanner.unknown_hint=true */ "
              "SELECT ID FROM Users"));
  } else {
    // Unknown hint with spanner_emulator.ignore_unknown_hints=true should
    // succeed.
    GOOGLESQL_EXPECT_OK(Query(
        "@{spanner_emulator.ignore_unknown_hints=true, unknown_hint=true} "
        "SELECT ID FROM Users"));
    GOOGLESQL_EXPECT_OK(
        Query("@{spanner_emulator.ignore_unknown_hints=true, "
              "spanner.unknown_hint=true} "
              "SELECT ID FROM Users"));
  }
}

TEST_P(QueryHintsTest, IgnoreUnknownHintsAppliesToChildNodes) {
  if (in_prod_env()) {
    GTEST_SKIP() << "ignore_unknown_hints is a spanner_emulator only hint";
  }
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    // Statement level should apply to scan hints.
    // In PG, table hints are attached to the table reference: Users /*@
    // force_index=... */.
    GOOGLESQL_EXPECT_OK(Query(
        "/*@ spanner_emulator.ignore_unknown_hints=true */ SELECT ID FROM "
        "Users /*@ unknown_hint=true */"));
  } else {
    // Statement level should apply to scan hints
    GOOGLESQL_EXPECT_OK(
        Query("@{spanner_emulator.ignore_unknown_hints=true} SELECT ID FROM "
              "Users@{unknown_hint=true}"));
  }
}

TEST_P(QueryHintsTest, IgnoreUnknownHintsExplicitlyDisabledFails) {
  if (in_prod_env()) {
    GTEST_SKIP() << "ignore_unknown_hints is a spanner_emulator only hint";
  }
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    // Explicitly disabled should still fail.
    EXPECT_THAT(
        Query("/*@ spanner_emulator.ignore_unknown_hints=false */ SELECT ID "
              "FROM Users /*@ unknown_hint=true */"),
        StatusIs(absl::StatusCode::kInvalidArgument));
  } else {
    // Explicitly disabled should still fail
    EXPECT_THAT(
        Query("@{spanner_emulator.ignore_unknown_hints=false} SELECT ID "
              "FROM Users@{unknown_hint=true}"),
        StatusIs(absl::StatusCode::kInvalidArgument));
  }
}

TEST_P(QueryHintsTest, IgnoreUnknownHintsInvalidTypeFails) {
  if (in_prod_env()) {
    GTEST_SKIP() << "ignore_unknown_hints is a spanner_emulator only hint";
  }
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    // Invalid value type for ignore_unknown_hints should fail.
    EXPECT_THAT(
        Query("/*@ spanner_emulator.ignore_unknown_hints=1 */ SELECT ID FROM "
              "Users"),
        StatusIs(absl::StatusCode::kInvalidArgument));
  } else {
    // Invalid value type for ignore_unknown_hints should fail
    EXPECT_THAT(
        Query("@{spanner_emulator.ignore_unknown_hints=1} SELECT ID FROM "
              "Users"),
        StatusIs(absl::StatusCode::kInvalidArgument));
  }
}

TEST_P(QueryHintsTest, IgnoreUnknownHintsKnownHintInvalidValueFails) {
  if (in_prod_env()) {
    GTEST_SKIP() << "ignore_unknown_hints is a spanner_emulator only hint";
  }
  if (dialect_ == database_api::DatabaseDialect::POSTGRESQL) {
    // Known hint with invalid value should still fail even with
    // ignore_unknown_hints=true. (force_index expects string, got bool)
    EXPECT_THAT(
        Query("/*@ spanner_emulator.ignore_unknown_hints=true */ SELECT ID "
              "FROM Users /*@ force_index=true */"),
        StatusIs(absl::StatusCode::kInvalidArgument));
  } else {
    // Known hint with invalid value should still fail even with
    // ignore_unknown_hints=true.
    EXPECT_THAT(
        Query("@{spanner_emulator.ignore_unknown_hints=true} SELECT ID FROM "
              "Users@{force_index=true}"),
        StatusIs(absl::StatusCode::kInvalidArgument));
  }
}

}  // namespace

}  // namespace test
}  // namespace emulator
}  // namespace spanner
}  // namespace google
